version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  sdkman: joshdholtz/sdkman@0.2.0


jobs:
  build_image:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - sdkman/setup-sdkman
      - sdkman/sdkman-install:
          candidate: java
          version: 21-graalce
      - run:
          name: "spring-boot:build-image"
          command: "./mvnw -Pnative spring-boot:build-image -DskipTests"
      - docker/check:
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD
      - docker/push:
          image: maelstrom0x8/service-registry
          tag: $CIRCLE_TAG

workflows:
  build-native-image:
    jobs:
      - build_image:
          context:
            - aeros-ctx
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
