eureka:
  instance:
   hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: false

spring:
  application:
    name: service-registry
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      enabled: false

server:
  port: 8761
  shutdown: GRACEFUL
